### ISSUE TITLE
Bugs in Python SpikerStream Code.

### ISSUE THREAD

**Issue by DamianJLin** [PHYS3888/SpikerStream#2]
Looking at the repo, this seems to have been translated to Python with a few errors.
```python
def process_data(data):
    data_in = np.array(data)
    result = []
    i = 1
    while i < len(data_in)-1:
        if data_in[i] > 127:
            # Found beginning of frame
            # Extract one sample from 2 bytes
            intout = (np.bitwise_and(data_in[i],127))*128
            i = i + 1
            intout = intout + data_in[i]
            result = np.append(result,intout)
        i=i+1
    return result
```
I think it should be changed to.
```python
def process_data(data):
    data_in = np.array(data)
    result = []
    i = 0  #####  Python indexing starts from 0
    while i <= len(data_in)-1:  ###### Judging by the MATLAB code, we want this line to run last when we are on the second-last entry in the array.
        if data_in[i] > 127:
            # Found beginning of frame
            # Extract one sample from 2 bytes
            intout = (np.bitwise_and(data_in[i],127))*128
            i = i + 1
            intout = intout + data_in[i]
            result = np.append(result,intout)
        i = i + 1
    return result
```
I don't have a SpikerBox with me at the moment to test this, however. Can possibly do so on Monday.

**Comment by benfulcher** [comment]
Looks right to me—have a test and let us know how it goes. Would be great to incorporate these fixes.

**Comment by DamianJLin** [comment]
The other thing I'm not sure about is why the code omits array elements less than 127 from the return array (the same thing happens in the MATLAB code). I'll check with whoever wrote the original code (I think it was Alessandro?) on Monday and test it.

**Comment by benfulcher** [comment]
Yep I think Alessandro originally made this conversion—he'd be the best to quiz about it. Speaking of quizzes, don't forget to submit your final PHYS3888 quiz.

**Comment by DamianJLin** [comment]
My SpikerStream_Python3_Script.py fixes this.
